# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.hostname = 'centos7'
    centos.vm.synced_folder "./results", "/vagrant"

    centos.vm.network "private_network", type: "dhcp"

    centos.vm.provision "shell", inline: <<-SHELL
      sudo yum -y update
      sudo yum -y install -y openscap-scanner scap-security-guide
    SHELL
  end

  config.vm.define "fedora" do |fedora|
    fedora.vm.box = "CornePlas/fedora23-lxde-puppet"
    fedora.vm.hostname = "fedora23"
    fedora.vm.network "private_network", type: "dhcp"
    fedora.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = true
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
    end
    
    fedora.vm.provision "shell", inline: <<-SHELL
      sudo dnf -y update
      sudo dnf -y install -y openscap-scanner scap-security-guide scap-workbench
    SHELL
  end


   #vbguest plugin specifics:
  config.vbguest.auto_update = true
  config.vbguest.no_remote = true

end
